### PR TITLE
fix 'getBool' to make it compatible with the latest Nim

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by euantorano** [comment]
Tests are failing but they’re unrelated to this change. I’ll have a look at them later.

**Comment by narimiran** [comment]
`lib/system.nim(207, 11) Error: undeclared identifier: 'is'`

This usually means that there's some version-mismatch going on between `lib/system.nim` and Nim version.

**Comment by euantorano** [comment]
The error I’m seeing is this: 

```
/Users/andreasrumpf-mac/projects/nim/lib/pure/includes/oserr.nim(85) raiseOSError
379Error: unhandled exception: No such file or directory [OSError]
```

I’ve opened another issue to look into it, which I’ll do on my lunch break.

**Comment by narimiran** [comment]
Open the fold above it which starts with ```# Simply replacing "master" with `$nim_branch` everywhere means we can reuse``` and you'll see the error I highlighted.

Those two might be related — i.e. there is some version mismatch happening.

**Comment by euantorano** [comment]
Ah, ok. I’ll have a look.

**Pull request merged**
